# Generated by Django 5.1.6 on 2025-02-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminders',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
